baseURL = "https://www.westharlemwindow.com/"
languageCode = "en-us"
title = "West Harlem Window"
theme = "mainroad"
#theme = "hugo-universal-theme"
#theme = "zzo"

enableEmoji = true

# unsafe = true lets it parse html tags, such as <br/>
 [markup.goldmark.renderer]
      unsafe = true

[Params]
#  toc = true
    #What sections have their contents displayed on the homepage
 mainSections = ["posts"]

[Params.logo]
  title = "West Harlem Window" # Logo title, otherwise will use site title
  subtitle = "Hamilton Heights, Manhattanville, Sugar Hill, and more" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["sidemenu","recent", "categories", "taglist", "social", "languages", "snap", "gcal"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  #facebook = "mostlydifferent"
  #twitter = "mostlydiff"
  instagram = "westharlemwindow"
  #linkedin = "alexsramek"
  #telegram = "username"
  #github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  email = "westharlemwindow@gmail.com"


